# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Mytech' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
        pod 'AFNetworking'
        pod 'SocketRocket'
        pod 'MJRefresh'
        pod 'YYKit'
  #      pod 'YYModel'
  #      pod 'YYCategories'
  #      pod 'YYWebImage'
        pod 'Masonry'
        pod 'SDWebImage'
        pod 'WechatOpenSDK'
        pod 'Weibo_SDK'

  target 'MytechTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MytechUITests' do
    # Pods for testing
  end

end
